name: Continuous Integration
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env: # Define environment variables for the entire job here, using secrets
        NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
            node-version: '18'
    - name: Install Dependencies
      run: npm install
    # - name: Run Tests
    #   run: npm test
    #
    - name: Build
      run: npm run build
